save_dir: ./saved_models
save_name: freematch_cifar10_40_0_relation
resume: False
load_path: None
overwrite: True
use_tensorboard: True
epoch: 1
num_train_iter: 1048576
num_eval_iter: 5000
num_labels: 40
batch_size: 64
eval_batch_size: 1024
hard_label: True
T: 0.5
ulb_loss_ratio: 1.0
ent_loss_ratio: 0.0
uratio: 7
ema_m: 0.999
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
amp: False
net: WideResNet
net_from_name: False
depth: 28
widen_factor: 2
leaky_slope: 0.1
dropout: 0.0
data_dir: ./data
dataset: cifar10
train_sampler: RandomSampler
num_classes: 10
num_workers: 1
alg: freematch
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10039
dist_backend: nccl
gpu: 0
mce_loss: MMXX
mce_lambd: 1.0
mce_mu: 1.0
mce_gamma: 0.003
mce_tau: 1.0
mce_order: 3
use_feature: False